### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by iProgYou** [teriley138/myTubeClone#4]
# Frontend Routes
- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)
## Comments
- Not sure if this is incomplete or just missing several things. Let me know if you need some guidance

**Comment by teriley138** [comment]
Hey Zach, I think it is a little bit of both. I know that it is incomplete and I need some guidance. I'm having trouble thinking about what the App is meant to be like in terms of the MVP that youtube is assigned. I'm not really exactly sure how uploading videos is a full CRUD feature. Im not sure how "update" will work for a video upload feature. I see CRD just not the U. I imagined for a CRUD feature I would have been doing some kind of user or content creator profile. Also in terms of youtube and the MVP list I can't really think of other pages to go to besides home page, sign up page, video play page. I know there is more on the real youtube site. But those things don't seem to be part of my MVP list. So yeah I do need a little guidance.

 But I think I am also struggling with this because Im so unsure of how the test is going to go on Monday and I am feeling very nervous about that. I have one failed test so I have to pass that test. I want to spend all my time focusing on passing that test but I know I have to get the full-stack planned but I am having real struggle focusing on it or thinking about it deeply. I'm hoping with some more assessment prep I can relax about it a little bit but Im just feeling the pressure a lot and feeling very uptight about it.

**Comment by teriley138** [comment]
ok I think that these frontend routes are better and seem like I have them much more thought out. I added upload/edit form routes. Updated the splash page to be a video index page and have it connected to a videoIndex component and videoIndexItem. I also showed that the show page will be connected with a videoComments component.

**Comment by iProgYou** [comment]
Looks great!
